# Generated by Django 5.0.7 on 2024-07-22 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=500)),
                ('Image_url', models.URLField(max_length=700, null=True)),
                ('Portfolio', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=400)),
                ('Review_text', models.TextField(max_length=900)),
                ('Recommend', models.BooleanField(default=False)),
                ('Date', models.DateField(blank=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='aesthete.user')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='no name', max_length=400)),
                ('Start_date', models.DateField(blank=True, null=True)),
                ('End_Date', models.DateField(blank=True, null=True)),
                ('Content', models.FileField(default='no content', upload_to='')),
                ('Description', models.TextField(default='no description', max_length=800)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='aesthete.user')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
    ]
