# Generated by Django 5.0.7 on 2024-07-22 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=500)),
                ('image_url', models.URLField(max_length=700, null=True)),
                ('portfolio', models.FileField(blank=True, null=True, upload_to='users/portfolios/')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('review_text', models.TextField(max_length=900)),
                ('recommend', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='aesthete.user')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=400)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_Date', models.DateField(blank=True, null=True)),
                ('content', models.FileField(blank=True, null=True, upload_to='projects/contents/')),
                ('description', models.TextField(default='no description', max_length=800)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='aesthete.user')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
    ]
