# Generated by Django 5.0.7 on 2024-07-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesthete', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Content',
            field=models.FileField(blank=True, null=True, upload_to='./aesthete/Content'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Portfolio',
            field=models.FileField(blank=True, null=True, upload_to='./aesthete/Portfolio'),
        ),
    ]
