# Generated by Django 5.0.7 on 2024-07-27 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aesthete', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='portfolio',
            table='portfolios',
        ),
    ]
