# Generated by Django 5.0.7 on 2024-07-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesthete', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='content',
        ),
        migrations.AddField(
            model_name='project',
            name='inspiration',
            field=models.URLField(max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='portfolio',
            field=models.URLField(max_length=700, null=True),
        ),
    ]
