# Generated by Django 5.0.7 on 2024-07-23 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aesthete', '0002_remove_project_content_project_inspiration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='end_Date',
            new_name='end_date',
        ),
    ]
